mybatis:
  mapper-locations: classpath.mappers/*xml
  type-aliases-package: com.example.glxt.mybatis.entity
server:
  port: 9001
spring:
  application:
    name: glxt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: 123456
    url: jdbc:mysql://localhost:3306/glxt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
